branch-defaults:
  default:
    environment: venv
    group_suffix: null
environment-defaults:
  venv:
    branch: null
    repository: null
global:
  application_name: frisbee-db
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
